name: Multilinters

on:
  push:

jobs:

  build:
    name: Check code
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.42
          args: -E gosec,goconst,nestif,interfacer,bodyclose,rowserrcheck
